### ISSUE TITLE
Next UI Update To-do List

### ISSUE THREAD

**Issue by AquaDragon** [kevinddchen/machikoro#145]
I made a to-do list in 2023 to update the UI, but was not able to work on it yet so I'll just leave my notes here in case I pick it up again.

- [ ] Add border to cards to distinguish between different expansions
- [ ] Add background to the different 'decks' (e.g. 1-6, 7+, purple)
- [ ] Add indicator to chat tab when there is a new unread message'
- [ ] Fix overflow text in Member's Only Club

Feel free add and/or suggest new items for the next UI update.
